services:
  - type: web
    name: mcp-playwright
    env: docker
    plan: starter
    autoDeploy: true

    # Pull the public image from Docker Hub
    image:
      url: docker.io/mcp/playwright:latest

    # MCP listens on 8931
    ports:
      - port: 8931
        protocol: tcp

    # Start MCP exactly like you do locally
    startCommand: >
      npx @playwright/mcp@latest
      --port 8931
      --host 0.0.0.0
      --browser chromium
      --allowed-hosts *
      --no-sandbox

    # Simple TCP healthcheck
    healthCheck:
      type: tcp
      port: 8931
