services:
  - type: web
    name: mcp-playwright
    env: docker
    plan: free
    autoDeploy: true

    # Build a minimal image that starts MCP on $PORT
    dockerfilePath: docker/mcp.Dockerfile
    dockerContext: .

    # HTTP health check (Render hits this path)
    healthCheckPath: /

    # Env you may tune without changing the image
    envVars:
      - key: ALLOWED_HOSTS # tighten later: "your-app.vercel.app,fishai.app"
        value: "*"
      - key: NODE_ENV
        value: production
