services:
  - type: web
    name: mcp-playwright
    env: docker
    plan: starter
    autoDeploy: true

    # Use the official Playwright MCP image from Docker Hub
    image:
      url: docker.io/mcp/playwright:latest

    # Render assigns a dynamic $PORT — bind MCP to it.
    # (Health check is HTTP; default path "/" is fine.)
    startCommand: >
      sh -lc 'npx @playwright/mcp@latest
      --port "$PORT"
      --host 0.0.0.0
      --browser chromium
      --allowed-hosts "*"   # tighten in prod
      --no-sandbox'

    healthCheckPath: /

    # Optional environment variables you may want to pin now or later
    envVars:
      # Example: restrict allowed hosts (replace with your actual domains)
      # - key: ALLOWED_HOSTS
      #   value: your-app.vercel.app,api.yourdomain.com
      # Then use: --allowed-hosts $ALLOWED_HOSTS
      - key: NODE_ENV
        value: production
