services:
  - type: web
    name: mcp-playwright
    env: docker
    plan: free
    autoDeploy: true

    dockerfilePath: docker/mcp.Dockerfile
    dockerContext: .

    # Render does HTTP health checks; default "/" is fine
    healthCheckPath: /

    envVars:
      # tighten later to your Vercel/custom domains
      - key: ALLOWED_HOSTS
        value: "*"
      - key: NODE_ENV
        value: production
