services:
  - type: web
    name: mcp-playwright
    env: docker
    plan: free
    autoDeploy: true

    image:
      url: docker.io/mcp/playwright:latest

    # MCP already runs on port 8931 inside container
    healthCheckPath: /

    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_HOSTS
        value: "*" # or your-vercel-domain.vercel.app
